baseURL = 'https://alexandredoyen29.github.io/'
languageCode = 'fr-fr'
title = "Page personnelle d'Alexandre DOYEN"
theme = "terminal"
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
copyright = "© Alexandre DOYEN, 2024"
[languages]
  [languages.fr]
    contentDir = 'content/fr'
    disabled = false
    languageCode = 'fr-FR'
    languageDirection = 'ltr'
    languageName = 'Français'
    title = "Page personnelle d'Alexandre DOYEN"
    weight = 1
    [languages.fr.params.logo]
      logoText = "Page personnelle d'Alexandre DOYEN"
    
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = "Alexandre DOYEN's personal webpage"
    weight = 2
    [languages.en.params.logo]
      logoText = "Alexandre DOYEN's personal webpage"
